### ISSUE TITLE
日历组件 iOS端显示混乱

### ISSUE THREAD

**Issue by yll2wcf** [youzouzou/wxapp#3]

**Comment by youzouzou** [comment]
@yll2wcf  已修改，之前用的是flex布局，没有用iphone测试过（结果现在借不到了）；目前改成了float浮动布局（第一行日期数据倒序，右浮动显示），不知行不行（如果还是不行，我后面借个机子再调试一下，或者只能重写样式了）

**Comment by youzouzou** [comment]
@yll2wcf 已修复，应该可以正常显示了
